### ISSUE TITLE
USWDS-Site - Add race/ethnicity guidance distinguishing between compliance/non-compliance collection

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2695] opened 2024-05-28 18:14 UTC
### Background
In our [CS/UX sync on 5/22/2024](https://docs.google.com/document/d/1IAs5HfPXmD3zWRVB5H_ia2HHXMb5yt-gUqJiUectGWQ/edit#heading=h.vlgr6wn9gopn) we discussed updating race/ethnicity guidance to distinguish between data collected for program compliance and data collected for usability research (e.g., understanding one's audience). A key difference between these two situations might be providing a "Prefer not to say" option for usability research but not for compliance data collection.

### Work to be completed
- Make content recommendations for updating guidance to distinguish between the collection of race/ethnicity data for program compliance vs. the collection of this data for other purposes, such as usability research

### Related issues

- USWDS-Site - Enhancement: Update race and ethnicity pattern based on SPD 15
[#2598](https://github.com/uswds/uswds-site/issues/2598)
- Crosswalk analysis between the revised SPD 15 and our current race and ethnicity pattern guidance [#2655](https://github.com/uswds/uswds-site/issues/2655)

**Comment by brunerae** [comment] 2024-10-23 01:49
Closing as duplicate of #2598

**Closed by brunerae** 2024-10-23 01:49 UTC
