### ISSUE TITLE
Improve header doc code block readability

### ISSUE THREAD

**Issue by greensteph** [uswds/uswds-site#696] opened 2018-12-18 14:04 UTC
## Description

The [header](https://v2.designsystem.digital.gov/components/headers/) code block in the docs is difficult to read:

- In the code highlighting the emphasis (red) is placed on the class attribute (class=) instead of the actual class making it difficult for the eye to focus on the priority item.
- The nesting structure is tough to follow, has lines beginning with \</li>.

## Additional information [optional]

Attached below: screenshot with the classes switched to change color emphasis.

![headers_red-green_swap](https://user-images.githubusercontent.com/11343071/50158766-ff23bb00-02a2-11e9-9d20-60a93cc9b1e3.png)

**Comment by maya** [comment] 2019-03-22 21:51
Here is the new code block designs that are implemented which includes `overflow: auto` for long lines and updated colors:
 
<img width="693" alt="Screen Shot 2019-03-22 at 2 45 11 PM" src="https://user-images.githubusercontent.com/5249443/54854765-4316c980-4cb1-11e9-864a-f947cb378c69.png">

The issue with the `</li>` formatting is a fractal issue that needs to be looked at on a case by case basis, it's dependent on how fractal outputs the nunjucks templates.

**Comment by maya** [comment] 2019-03-25 19:01
Issues with the "Basic header with megamenu" code sample readability persist:

<img width="725" alt="Screen Shot 2019-03-25 at 11 59 39 AM" src="https://user-images.githubusercontent.com/5249443/54946551-8b262e00-4ef5-11e9-9265-d7b21775dfa6.png">

This is related to how the sub-components are being pulled in.

**Comment by maya** [comment] 2019-03-25 19:16
This is also an issue with the side navigation.

**Comment by thisisdano** [comment] 2019-12-03 23:40
This is a "feature" that is also an irritating bug. The issue is less the display of the leading `</li>`s in some of the lines, but the fact that the code _needs to be written that way to display properly._

😬 

These items have meaningful whitespace" because they're set to display as `inline-block` — if the markup had the proper line breaks and indentation, there would be small gaps in-between the elements. Sad but true.

I would suggest that we close this issue, then open a new one to fix the `inline-block` technique used in these navs. They depend on meaningful whitespace and that will definitely result in inconsistent usage over time.

**Closed** 2021-02-25 21:39 UTC
Labels: enhancement, help wanted, priority: minor, ux
