### ISSUE TITLE
2.0 Migration guide

### ISSUE THREAD

**Issue by adborden** [uswds/uswds-site#701] opened 2019-02-01 16:42 UTC
## Description

USWDS users have been using v1.x for a while and have their own assumptions about how to import USWDS into their site. When switching to 2.0, some of these assumptions have changed, or are no longer recommended, or maybe even unsupported. A migration guide would compile the Release Notes into a step by step of how to take your v1 site and make it v2.

## Steps to reproduce the issue

N/A

## Additional information [optional]

N/A

**Comment by maya** [comment] 2019-03-26 03:28
Duplicate of https://github.com/uswds/uswds/issues/2536.

**Closed by maya** 2019-03-26 03:28 UTC
